.github/workflows/ci.yml, pyproject.toml
Apparantly, it doesn't *verify types*, it just checks a *local package* and propagates all errors from external packages (without providing any means to control this).
So for stub-only packages, `--ignoreexternal` is *always* required for the results to make any sense.
=> stop incorrectly using `basedpyright --verifytypes`

scipy-stubs/integrate/_ode.pyi, scipy-stubs/integrate/_quad_vec.pyi, scipy-stubs/integrate/_quadpack_py.pyi, scipy-stubs/integrate/_quadrature.pyi, scipy-stubs/sparse/_dok.pyi, scipy-stubs/special/_orthogonal.pyi
=> fix `scipy.integrate` quad integrand function signatures

.github/workflows/ci.yml, README.md, tests/stubtest/allowlist.txt
the following `scipy` packages are now required pass stubtest:
- `.cluster`
- `.constants`
- `.datasets`
- `.fft`
- `.fftpack`
- `.integrate`
- `.io.arff`, `.io.matlab`
- `.linalg`
- `.misc`
- `.odr`
- `.optimize`
- `.special`
- `.stats.contingency`, `.stats.distributions`
- `.version`
=> stubtest specific packages

.github/workflows/ci.yml, .pre-commit-config.yaml, pyproject.toml
- sync the `scipy-stubs` version to that of `scipy`, currently `1.14.1.0.dev0`
- stop using `pyright --verifytypes`: it's irrrelevant for stub-only packages
- remove the `py.typed`, because according to the [typing spec](https://typing.readthedocs.io/en/latest/spec/distributing.html#stub-only-packages):
> For stub-only packages adding a py.typed marker is not needed since the name *-stubs is 
enough to indicate it is a source of typing information.
=> fix version number and stop using `verifytypes`

poetry.lock, pyproject.toml, scipy-stubs/_lib/_ccallback.pyi
this also removes the need for the (mostly incomplete) `types-cffi` dependency
=> improved `scipy.LowLevelCallable`

README.md, scipy-stubs/linalg/_misc.pyi
with this, there are no more `Untyped` annotations within `scipy.linalg`
=> complete `scipy.linalg`

pyproject.toml
because `poetry` will otherwise leave `3.10` out
=> explicit python version pypi classifiers

scipy-stubs/_typing.pyi, scipy-stubs/fft/_realtransforms.pyi
This is the only function used by https://github.com/Toufool/AutoSplit, and I'd gladly replace my local https://github.com/Toufool/AutoSplit/tree/9588834e0881e8c09b449954f4c5c24f0e15bd14/typings/scipy for a community-based one.
I've also added and applied type aliases for "DCT type" and "normalization mode"
I'm not 100% certain about the numpy generic types.
=> complete `scipy.fft.dct`, and add relevant type aliases

scipy-stubs/signal/_savitzky_golay.pyi
Before this PR, the stub file `_savitzky_golay.pyi` had untyped annotations. This PR adds in the missing type annotations and improves previous ones.
The improvements are:
1. Use `op.CanIndex` instead of `int` for the `axis` parameter.
2. Use Literals to type hint certain strings for `use` and `mode` parameters
This file tends to use `int` and `float` a lot which could perhaps be replaced by `AnyInt` and `AnyReal` however, some parameters like `window_length` are used as shapes in calls to functions like `np.zeros` which don't accept `np.bool_`.
For simplicity I left the type annotations as the builtin python types but I am open to using more general type annotations to allow numpy dtypes as well. It just might take a bit more testing to check the allowed types.
=> complete `scipy.signal._savitzky_golay`

poetry.lock, pyproject.toml
release notes:
- https://github.com/KotlinIsland/basedmypy/releases/tag/v2.7.0
- https://mypy.readthedocs.io/en/stable/changelog.html#mypy-1-13
=> bump to `basedmypy 2.7.0` (`mypy 1.3.0`)

scipy-stubs/signal/_spectral_py.pyi, tests/signal/test_spectral.pyi
Contributes to completing #99.
I added type stubs to the stub file `signal/_spectral_py.pyi` and tests for the function overloads I added.
I discovered that the function `lombscargle` was recently updated to include new parameters which also expands the possible return types (see PR scipy/scipy#21277). It also adds inline type stubs which might be an issue.
I did not type stub against this new version though because I think it is still in the dev branch and is not part of a release.
Also I saw that the function `periodogram`'s docs don't specify that `None` is allowed for the argument `window` but the body explicitly checks for `None`. Therefore I allowed `None` to be passed in as well. This is a bit annoying because the type annotation is no longer consistent with other `window` …
=> `signal`: Add type stubs to `_spectral_py.pyi`.

scipy-stubs/stats/_qmc.pyi, scipy-stubs/stats/_qmc_cy.pyi, tests/stats/qmc/test_scale.pyi
=> fix incorrectly rejected `ndarray` in `scipy.stats.qmc`

scipy-stubs/interpolate/_cubic.pyi, scipy-stubs/interpolate/_interpolate.pyi
this completes the annotations for the following `scipy.interpolate` members:
- `Akima1DInterpolator`
- `CubicHermiteSpline`
- `CubicSpline`
- `PchipInterpolator`
- `pchip_interpolate`
- `_interpolate._PPolyBase`
- `PPoly` (except for `tck` of `.from_spline()`)
- `BPoly`
- `NdPPoly`
- `lagrange`
towards #107
fixes #177
=> complete `scipy.interpolate._cubic`

scipy-stubs/optimize/_constraints.pyi, scipy-stubs/optimize/_trustregion_constr/canonical_constraint.pyi, scipy-stubs/optimize/_trustregion_constr/equality_constrained_sqp.pyi, scipy-stubs/optimize/_trustregion_constr/minimize_trustregion_constr.pyi, scipy-stubs/optimize/_trustregion_constr/projections.pyi, scipy-stubs/optimize/_trustregion_constr/tr_interior_point.pyi
This mostly affects the internal constraint-based machinery within `scipy.optimize`. The only affected public members are
- `Bounds`
- `LinearConstraint`
- `NonlinearConstraint`
225 `Untyped` annotations were resolved
=> `optimize`: complete `_constraints` and `_trustregion_constr.*`

scipy-stubs/optimize/_root.pyi, scipy-stubs/optimize/_root_scalar.pyi, scipy-stubs/optimize/_typing.pyi, scipy-stubs/optimize/_zeros_py.pyi, scipy-stubs/optimize/zeros.pyi
This completes the annotations (i.e. filled in every `Untyped*`) of the following public `scipy.optimize` members:
- `root`
- `root_scalar`
- `brentq`
- `brenth`
- `ridder`
- `bisect`
- `newton`
- `toms748`
- `RootResult`
[docs](https://docs.scipy.org/doc/scipy-1.14.1/reference/optimize.html#root-finding)
towards #102 (-60)
=> `optimize`: complete the root-finding functions

scipy-stubs/optimize/_minpack_py.pyi
the common denominator of these functions, is that they all live in the `scipy.optimize._minpack_py` module
docs:
- [`scipy.optimize.curve_fit`](https://docs.scipy.org/doc/scipy-1.14.1/reference/generated/scipy.optimize.curve_fit.html)
- [`scipy.optimize.leastsq`](https://docs.scipy.org/doc/scipy-1.14.1/reference/generated/scipy.optimize.leastsq.html)
- [`scipy.optimize.fsolve`](https://docs.scipy.org/doc/scipy-1.14.1/reference/generated/scipy.optimize.fsolve.html)
towards #102 (-29)
=> `optimize`: complete `curve_fit`, `leastsq`, and `fsolve`

scipy-stubs/optimize/_direct_py.pyi
The annotations had been copied-over by `stubgen` from `scipy`'s own inline annotations, which were (without exception) either too narrow or invalid...
[docs](https://docs.scipy.org/doc/scipy-1.14.1/reference/generated/scipy.optimize.direct.html)
towards #102 (-2)
=> `optimize`: fix and complete `direct`

scipy-stubs/optimize/_differentiable_functions.pyi
This affects the following classes of the private `scipy.optimize._differentiable_functions` module:
- `ScalarFunction`
- `VectorFunction`
- `LinearVectorFunction`
- `IdentityVectorFunction`
These have all been made optionally generic on the scalar-type `x` (the floating input vector).
It's not (yet) possible annotate the array-api support, as discussed in #140.
---
towards #102 (-73)
=> `optimize`: complete `_differentiable_functions` (private)

scipy-stubs/signal/_short_time_fft.pyi
This contributes to closing #99.
I saw that there was a single `Untyped` left so here is a PR to fix that.
=> `signal`: Replace the final `Untyped` in `_short_time_fft.pyi`.

scipy-stubs/optimize/_shgo_lib/_complex.pyi, scipy-stubs/optimize/_shgo_lib/_vertex.pyi
=> `optimize`: complete `_shgo_lib` (private)

README.md
=> document that `scipy-stubs` is installable with conda

.github/workflows/ci.yml, scipy-stubs/integrate/_quad_vec.pyi, scipy-stubs/optimize/_optimize.pyi
resolves #81
this also caught a minor bug in `optimize._optimize` and one in `integrate.quad_vec` with `numpy<2.2`
=> test with the oldest supported numpy version in the CI

scipy-stubs/optimize/_trlib/__init__.pyi, scipy-stubs/optimize/_trlib/_trlib.pyi, scipy-stubs/optimize/_trustregion.pyi, scipy-stubs/optimize/_trustregion_dogleg.pyi, scipy-stubs/optimize/_trustregion_exact.pyi, scipy-stubs/optimize/_trustregion_krylov.pyi, scipy-stubs/optimize/_trustregion_ncg.pyi
=> `optimize`: complete `_trlib` and `_trustregion*` (private)

scipy-stubs/optimize/_lbfgsb_py.pyi
this completes the following `scipy.optimize` members:
- [`fmin_l_bfgs_b`](https://docs.scipy.org/doc/scipy-1.14.1/reference/generated/scipy.optimize.fmin_l_bfgs_b.html) (legacy)
- [`LbfgsInvHessProduct`](https://docs.scipy.org/doc/scipy-1.14.1/reference/generated/scipy.optimize.LbfgsInvHessProduct.html)
towards #102
=> `optimize`: complete `fmin_l_bfgs_b` and `LbfgsInvHessProduct`

scipy-stubs/linalg/_basic.pyi
This improves the following `scipy.linalg` function signatures:
- `solve`
- `solve_triangular`
- `solve_banded`
- `solveh_banded`
- `solve_toeplitz`
- `inv`
- `det`
- `lstsq`
- `pinv`
- `matrix_balance`
- `matmul_toeplitz`
towards #233
=> `linalg._basic`: add overloads for shapes and dtypes

scipy-stubs/linalg/_decomp.pyi, scipy-stubs/linalg/_decomp_cholesky.pyi, scipy-stubs/linalg/_decomp_cossin.pyi, scipy-stubs/linalg/_decomp_ldl.pyi, scipy-stubs/linalg/_decomp_lu.pyi, scipy-stubs/linalg/_decomp_lu_cython.pyi, scipy-stubs/linalg/_decomp_polar.pyi, scipy-stubs/linalg/_decomp_qr.pyi, scipy-stubs/linalg/_decomp_qz.pyi, scipy-stubs/linalg/_decomp_schur.pyi, scipy-stubs/linalg/_decomp_svd.pyi, scipy-stubs/linalg/_decomp_update.pyi, scipy-stubs/linalg/decomp.pyi, scipy-stubs/linalg/decomp_cholesky.pyi, scipy-stubs/linalg/decomp_lu.pyi, scipy-stubs/linalg/decomp_qr.pyi, scipy-stubs/linalg/decomp_schur.pyi, scipy-stubs/linalg/decomp_svd.pyi
This improves the following public `scipy.linalg` function signatures:
- `cholesky[_banded]`
- `cho_solve[_banded]`
- `cho_factor`
- `eig[_banded]`
- `eigvals[_banded]`
- `eigh[_tridiagonal]`
- `eigvalsh[_tridiagonal]`
- `cossin`
- `hessenberg`
- `ldl`
- `lu`
- `lu_factor`
- `lu_solve`
- `polar`
- `qr`
- `qr_multiply`
- `rq`
- `qz`
- `ordqz`
- `schur`
- `svd`
- `svdvals`
- `diagsvd`
- `orth`
- `null_spaces`
- `subspace_angles`
- `qr_delete`
- `qr_insert`
- `qr_update`
- `rsf2csf`
- `cdf2rdf`
towards #233
=> `linalg._decomp*`: add overloads for shapes and dtypes

scipy-stubs/linalg/_misc.pyi
This updates the `scipy.linalg.norm` signature to better take the shjape and dtype into account, and now uses a total of 15 overloads.
Towards #233
=> `linalg`: improved `norm` signature

README.md
It's a bit flashy, but all very true.
closes #248
=> Add a highlights section in `README.md`

.pre-commit-config.yaml, pyproject.toml, uv.lock
https://github.com/astral-sh/ruff/releases/tag/0.8.2
=> ⬆️ bump `ruff` to `0.8.2`

scipy-stubs/spatial/_qhull.pyi
This improves the shape-typing of the following  public `scipy.spatial` members:
- `Delaunay`
- `ConvexHull`
- `Voronoi`
- `HalfspaceIntersection`
- `tsearch`
Additionally, an internal (private) type-check-only protocol was added for the cython struct `DelaunayInfo_t` in `_qhull.pxd`, which is used in other cython modules such as 
`scipy.interpolate.interpnd`.
=> ✨ improve `spatial._qhull`

scipy-stubs/interpolate/_bsplines.pyi, scipy-stubs/interpolate/_ndbspline.pyi
This affects the following public `scipy.interpolate` members:
- `NdBSpline`
- `BSpline`
- `make_interp_spline`
- `make_lsq_spline`
- `make_smoothing_spline`
towards #101 (-68)
=> ✨ `interpolate`: complete `_bsplines` and `_ndbspline`

scipy-stubs/interpolate/_rbf.pyi, scipy-stubs/interpolate/_rbfinterp.pyi
This affects the following public `scipy.interpolate` classes:
- `RBFInterpolator`
- `Rbf` (legacy)
towards #101 (-32)
=> ✨ `interpolate`: complete `RBFInterpolator` and `Rbf`

scipy-stubs/interpolate/_dfitpack.pyi, scipy-stubs/interpolate/_fitpack_impl.pyi, scipy-stubs/interpolate/_fitpack_py.pyi
This completes the (univariate half) of the `scipy.interpolate` Python `FITPACK` modules (`_fitpack_impl` and `_fitpack_py`). This affects the following public `scipy.interpolate` functions:
- `splprep`
- `splrep`
- `splev`
- `splint`
- `sproot`
- `spalde`
The remaining half (`bisplrep`, `bisplev`, `insert`, `splder`, and `splantider`) will be addressed in a follow-up PR.
towards #101 (-29)
=> ✨ `interpolate`: complete `_fitpack*` (1/2)

scipy-stubs/interpolate/_fitpack_impl.pyi, scipy-stubs/interpolate/_fitpack_py.pyi
This affects the following public `scipy.interpolate` functions:
- `bisplrep`
- `bisplev`
- `insert`
- `splder`
- `splantider`
follows #275
towards #101 (-32)
=> ✨ `interpolate`: complete `_fitpack_impl` (2/2)

scipy-stubs/interpolate/_fitpack2.pyi
This affects the following `scipy.interpolate` members:
- `UnivariateSpline`
- `InterpolatedUnivariateSpline`
- `LSQUnivariateSpline`
- `BivariateSpline`
- `SphereBivariateSpline`
- `SmoothBivariateSpline`
- `SmoothSphereBivariateSpline`
- `LSQBivariateSpline`
- `LSQSphereBivariateSpline`
- `RectBivariateSpline`
- `RectSphereBivariateSpline`
towards #101 (-63)
=> ✨ `interpolate`: complete `_fitpack2`

scipy-stubs/interpolate/_bsplines.pyi, scipy-stubs/interpolate/_rgi.pyi
This affects the following `scipy.interpolate` members:
- `RegularGridInterpolator`
- `interpn`
towards #101 (-22)
=> ✨ `interpolate`: complete `_rgi`

scipy-stubs/signal/_filter_design.pyi
This affects the following public members of `scipy.signal`:
- `freqs`
- `freqs_zpk`
- `freqz`
- `freqz_zpk`
- `group_delay`
- `sosfreqz`
towards #99 (-30)
=> ✨ `signal`: complete frequency response functions in `_filter_design`

.github/workflows/ci.yml, scripts/version_bounds.py
apparently mypy was still using the latest numpy because it doesn't understand editable projects and has to be run in an isolated uv env which doesn't include the `uv pip install`'ed numpy version or the correct python version
=> 💚 fix `typetest-oldest-supported-numpy` CI job

scipy-stubs/optimize/_lbfgsb_py.pyi, scipy-stubs/sparse/linalg/_interface.pyi
This affects the following public `scipy.sparse.linalg` members:
- `LinearOperator`
- `aslinearoperator`
towards #100 (-26)
=> ✨ `sparse.linalg`: complete the `LinearOperator`s in `_interface`

scipy-stubs/sparse/linalg/_norm.pyi, scipy-stubs/sparse/linalg/_onenormest.pyi
This affects the following public members of [`scipy.sparse.linalg`](https://docs.scipy.org/doc/scipy-1.14.1/reference/sparse.linalg.html):
- `norm`
- `onenormest`
towards #100 (-28)
=> ✨ `sparse.linalg`: complete the matrix norm functions

scipy-stubs/sparse/linalg/_eigen/arpack/arpack.pyi
This affects the following public members of [`scipy.sparse.linalg`](https://docs.scipy.org/doc/scipy-1.14.1/reference/sparse.linalg.html):
- `eigs`
- `eigsh`
- `ArpackError`
- `ArpackNoConvergence`
towards #100 (-59)
=> ✨ `sparse.linalg`: complete `_eigen.arpack`

scipy-stubs/sparse/_construct.pyi
=> ✨ `sparse`: complete `kron[sum]`

scipy-stubs/sparse/linalg/_isolve/utils.pyi
=> ✨ `sparse`: complete `linalg._isolve.utils.*` (private)

README.md, scipy-stubs/sparse/linalg/_isolve/_gcrotmk.pyi, scipy-stubs/sparse/linalg/_isolve/iterative.pyi, scipy-stubs/sparse/linalg/_isolve/lgmres.pyi, scipy-stubs/sparse/linalg/_isolve/minres.pyi, scipy-stubs/sparse/linalg/_isolve/tfqmr.pyi, scipy-stubs/sparse/linalg/_isolve/utils.pyi
This affects the following `scipy.sparse.linalg` public members:
- `gcrotmk`
- `bicg`
- `bicgstab`
- `cg`
- `cgs`
- `gmres`
- `lgmres`
- `minres`
- `qmr`
- `tfqmr`
Closes #100
=> ✨ `sparse`: complete the remaining `sparse.linalg` functions

.mypyignore-todo, scipy-stubs/cluster/hierarchy.pyi, scipy-stubs/cluster/vq.pyi
=> 👽️ `cluster`: fix new stubtest errors

.pre-commit-config.yaml, pyproject.toml, uv.lock
`mdformat == 0.7.20` is completely broken: https://github.com/hukkin/mdformat/issues/501
=> ⬆️ bump `ruff` to `0.8.4` and disallow `mdformat==0.7.20`

README.md
- include installation instructions for the `scipy-typed` conda-forge exclusive deluxe combo-package-deal (quantum edition)
- a matrix of the installable packages
- removed the outdated `Untyped` table, and replaced it with more human-friendly "text".
- add a new "Contributing" section, containing some idea's on how you could help
- a slightly more pretentious podcast section
related to https://github.com/scipy/scipy.org/pull/595
=> 📝 several `README.md` improvements

scipy-stubs/interpolate/interpnd.pyi
ref scipy/scipy#22097
ref scipy/scipy#22099
cc @j-bowhay 
cc @h-vetinari
=> 💬 `interpolate`: fix scipy version in `interpnd` deprecation warning messages

scipy-stubs/special/_multiufuncs.pyi
The return types now depend on `diff_n`, and some float returns were corrected to complex.
Note that this doesn't affect any of the current releases.
=> 🐛 `special`: fix the 1.15 "multi-ufunc" signatures

pyproject.toml, uv.lock
... and reorganize the dependency groups
=> 📌 pin `scipy<1.16`

scipy-stubs/signal/_czt.pyi, scipy-stubs/signal/_filter_design.pyi
This affects the following public `scipy.signal` members:
- `CZT`
- `czt`
- `czt_points`
- `ZoomFFT`
- `zoom_fft`
- `iirdesign`
- `iirfilter`
- `iirnotch`
- `iirpeak`
- `iircomb`
- `gammatone`
- `butter`
- `cheby{1,2}`
- `ellip`
- `bessel`
- `buttord`
- `cheb{1,2}ord`
- `ellipord`
- `band_stop_obj`
- `buttap`
- `cheb{1,2}ap`
- `ellipap`
- `besselap`
- `normalize`
- `tf2{zpk,sos}`
- `spk2{tf,sos}`
- `sos2{tf,zpk}`
- `lp2{lp,hp,bp,bs}`
- `lp2{lp,hp,bp,bs}_zpk`
- `bilinear`
- `bilinear_zpk`
towards #99 (-157)
=> ✨ `signal`: complete `_filter_design`, fix and improve `_czt`

.github/workflows/publish-pypi.yml
Unlike optype, which triggers on tag push, this one will trigger on release creation (which hopefully also includes draft releases). Let's see which one I like better.
closes #263
=> 👷 PyPI trusted publishing workflow

scipy-stubs/signal/_arraytools.pyi, scipy-stubs/signal/_fir_filter_design.pyi, scipy-stubs/signal/_max_len_seq.pyi, scipy-stubs/signal/_max_len_seq_inner.pyi
This affects the following public members of `scipy.signal`:
- `kaiser_beta`
- `kaiser_atten`
- `kaiserord`
- `firwin`
- `firwin2`
- `firls`
- `remez`
- `minimum_phase`
- `max_len_seq`
towards #99 (-30)
=> ✨ `signal`: complete `_fir_filter_design.*` en `max_len_seq`

README.md, scipy-stubs/_typing.pyi, scipy-stubs/signal/_lti_conversion.pyi, scipy-stubs/signal/_ltisys.pyi
This affects the following public members of `scipy.signal`:
- `TransferFunction`
- `ZerosPolesGain`
- `StateSpace`
- `place_poles`
- `lsim`
- `dlsim`
- `bode`
- `dbode`
- `impulse`
- `dimpulse`
- `lti`
- `dlti`
- `step`
- `dstep`
- `freqresp`
- `dfreqresp`
closes #99 (-156)
=> ✨ `signal`: complete `_ltisys.*`

.github/workflows/ci.yml, scripts/generate_matrix.py
This reduces the required jobs by 3, resulting in ~33% faster CI runs.
=> 👷 exclude unsupported test matrix version combinations

codegen/mods.py, scipy-stubs/interpolate/_bary_rational.pyi, scipy-stubs/stats/_distribution_infrastructure.pyi, scipy-stubs/stats/_probability_distribution.pyi, scipy-stubs/stats/_resampling.pyi
The `FixTrailingComma` codemod only looked at pos-or-kw-only parameters, disregarding the pos-only and kw-only ones.
=> 🎨 fix and run the `FixTrailingComma` codemod

scipy-stubs/stats/_distn_infrastructure.pyi, tests/stats/test_rv_sample.pyi
closes #417
closes scipy/scipy#22327
=> 🐛 `stats`: fix `rv_discrete` sample constructor

scipy-stubs/signal/_ltisys.pyi
The following public `scipy.signal` classes are now (optionally) generic. Their type parameters bind to the scalar type of `.zeros`, `.poles` and the type of `.dt` (or `None` if continuous):
- `[d]lti`
- `TransferFunction`
- `ZerosPolesGain`
- `StateSpace`
This improves the annotations of following public members in `scipy.signal`, so that the signatures can better distinguish between real and complex input/output types.
- `place_poles`
- `[d]lsim`
- `[d]impulse`
- `[d]step`
- `[d]bode`
- `[d]freqresp`
---
closes #402
=> ✨ `signal`: generic `lti`, and `dlti` types

scipy-stubs/optimize/_nonlin.pyi
This affects the following public `scipy.optimize` members:
- `InverseJacobian`
- `KrylovJacobian`
- `BroydenFirst`
The scalar type of the `dtype` attribute of these types is now associated to their (optional) generic type-parameter.
---
closes #400
=> ✨ `optimize`: Generic `InverseJacobian` and related types

scipy-stubs/signal/_czt.pyi
This affects the following public `scipy.signal` members:
- `CZT`
- `ZoomFFT`
- `czt_points`
- `czt`
- `zoom_fft`
---
closes #401
=> ✨ `signal`: improvements related to `czt` and `zoom_fft`

pyproject.toml, uv.lock
https://github.com/astral-sh/ruff/releases/tag/0.9.3
=> ⬆️ bump `ruff` to `0.9.3`

pyproject.toml
=> 🔧  scipy.org as homepage and add scipy-dev  as maintainer

pyproject.toml, uv.lock
relevant release notes:
- https://github.com/DetachHead/basedpyright/releases/tag/v1.26.0
- https://github.com/microsoft/pyright/releases/tag/1.1.393
- https://github.com/DetachHead/basedpyright/releases/tag/v1.25.0
- https://github.com/microsoft/pyright/releases/tag/1.1.392
=> ⬆️ basedpyright 1.26.0 (pyright 1.1.393)

scipy-stubs/signal/_peak_finding.pyi
=> Bugfix: Add plain number option for find_peaks argument prominence

pyproject.toml, uv.lock
https://github.com/jorenham/optype/releases/tag/v0.9.1
=> 📌 bump `optype` to `0.9.1`

scipy-stubs/optimize/_minimize.pyi, tests/optimize/minimize_scalar.pyi
This fixes a `1.15.2.0` regression that was introduced in https://github.com/scipy/scipy-stubs/pull/428.
The `optimize.minimize_scalar` now also accepts `numpy.polynomial` class instances.
Closes #465
=> 🐛 `optimize`: allow calling `minimize_scalar` without a `bracket`

scipy-stubs/spatial/transform/_rotation.pyi
Current definition
>  _RotAxisSeq: TypeAlias = L["xyz", "xzy", "yzx", "yxz", "zxy", "zyx", "XYZ", "XZY", "YXZ", "YZX", "ZXY", "ZYX"]
only includes Tait-Bryan sequences.
Documentation at:
https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.transform.Rotation.as_euler.html
shows its viable to use proper Euler also.
> [0, 180] degrees if first and third axes are the same (like zxz)
=> 🐛 `spatial.transform`: accept proper Euler angles in `Rotation.as_euler`

pyproject.toml, uv.lock
- bump `basedpyright` to `1.28.4
- bump `ruff` to `0.11.2`
=> ⬆️ update development dependencies

pyproject.toml, scipy-stubs/optimize/_slsqp_py.pyi, scipy-stubs/optimize/_zeros_py.pyi, uv.lock
https://github.com/jorenham/optype/releases/tag/v0.9.3
=> 📌 bump `optype` to `0.9.3`

scipy-stubs/interpolate/_rgi.pyi, tests/interpolate/_rgi.pyi
=> 🐛 `interpolate`: accept `ndarray` for `points` in `RegularGridInterpolator`

scipy-stubs/optimize/_minimize.pyi, tests/.ruff.toml, tests/optimize/minimize.pyi
=> 🐛 `optimize`: accept a scalar for `x0` in `minimize`

scipy-stubs/optimize/_minimize.pyi
This removes the need for a workaround in colour-science/colour#1342, and closes #495.
=> ✨ `optimize`: narrowed `OptimizeResult.{fun,x}` attrs for `minimize[_scalar]`

scipy-stubs/optimize/_milp.pyi
closes #510 
Updated key name "min_rel_gap" -> "mip_rel_gap" to match `scipy.optimize.milp` docs.
=> Correct key name in :class:`_OptionsMILP`

pyproject.toml
closes #512 
Removed deprecated license trove classifier. This should allow the PP005 check in the PR `lint` job to pass.
=> Remove License Trove Classifier from `pyproject.toml`

scipy-stubs/signal/_peak_finding.pyi
=> 🐛 `signal`: accept numbers as args to `width` and `plateau_size` for `find_peaks()`

.mypyignore-todo, scipy-stubs/interpolate/_fitpack2.pyi
A `maxit=20` constructor parameter has been added to the `interpolate.RectBivariateSpline`  class.
=> 👽️ scipy 1.16 change for `interpolate.RectBivariateSpline`

.mypyignore-todo, scipy-stubs/interpolate/_bsplines.pyi
An `axis=0` keyword-only parameter has been added to the `interpolate.make_smoothing_spline` function, which now has batch support according to the release notes.
=> 👽️ scipy 1.16 change for `interpolate.make_smoothing_spline`

.mypyignore-todo, scipy-stubs/optimize/_differentiable_functions.pyi, scipy-stubs/optimize/_lsq/dogbox.pyi, scipy-stubs/optimize/_lsq/least_squares.pyi, scipy-stubs/optimize/_lsq/trf.pyi, scipy-stubs/optimize/minpack.pyi
from the 1.16.0rc1 brelease notes:
> `scipy.optimize.least_squares` has a new `callback` argument that is applicable
to the `trf` and `dogbox` methods. `callback` may be used to track
optimization results at each step or to provide custom conditions for
stopping.
=> 👽️ scipy 1.16 changes for `optimize.least_squares`

.mypyignore-todo, scipy-stubs/optimize/_numdiff.pyi
The private `scipy.optimize._numdiff.approx_derivative` function has gotten two new parameters: `full_output` and `workers`.
=> 👽️ scipy 1.16 changes for `optimize._numdiff`

.mypyignore-todo, scipy-stubs/optimize/_slsqp_py.pyi, scipy-stubs/optimize/slsqp.pyi
The deprecated `scipy.optimize.slsqp.zeros` function has been removed. 
**The [1.16.0rc1 release notes](https://github.com/scipy/scipy/releases/tag/v1.16.0rc1) do not mention this.**
=> 👽️ scipy 1.16 changes for `optimize.slsqp`

.mypyignore-todo, scipy-stubs/spatial/transform/_rotation.pyi
A new public function has been added to the private `scipy.spatial.transform._rotation` module, `compose_quat`, with signature `(f64[:, :], f64[:, :]) -> f64[:, :]`.
=> 👽️ scipy 1.16 additions for `spatial.transform._rotation`

.mypyignore, .mypyignore-todo, scipy-stubs/special/_support_alternative_backends.pyi
The private `scipy.special._support_alternative_backends` module was changed to additionally export the `stdtrit` ufunc through its `__all__`.
=> 👽️ scipy 1.16 changes for `special._support_alternative_backends`

scipy-stubs/stats/_hypotests.pyi
This affects the following public `scipy.stats` functions:
- `barnard_exact`
- `boschloo_exact`
- `cramervonmises`
- `cramervonmises_2samp`
- `epps_singleton_2samp`
- `somersd`
=> ✨ `stats`: improved hypothesis test function return type annotations

.mypyignore-todo, scipy-stubs/stats/_stats_py.pyi, scipy-stubs/stats/stats.pyi
From the [`1.16.0rc1` release notes](https://github.com/scipy/scipy/releases/tag/v1.16.0rc1):
> An `equal_var` keyword was added to (...) `scipy.stats.f_oneway` (enables Welch ANOVA).
=> 👽️ scipy 1.16 changes for `stats.f_oneway`

scipy-stubs/stats/_stats_py.pyi
From the [`1.16.0rc1` release notes](https://github.com/scipy/scipy/releases/tag/v1.16.0rc1):
> Support for inference of the two sets of measurements from the single
argument `x` has been removed from `scipy.stats.linregress`. The data
must be specified separately as `x` and `y`.
=> 👽️ scipy 1.16 expired deprecation for `stats.linregress`

.mypyignore-todo, scipy-stubs/stats/_stats_py.pyi, scipy-stubs/stats/stats.pyi
From the [`1.16.0rc1` release notes](https://github.com/scipy/scipy/releases/tag/v1.16.0rc1):
> Support for `axis`, `nan_policy`, and `keepdims` keywords was added to (...) `scipy.stats.kendalltau`,
`scipy.stats.weightedtau`, (...)
=> 👽️ scipy 1.16 changes for `stats.{kendall,weighted}tau`

.github/workflows/ci.yml, pyproject.toml
All scipy 1.16.0rc1 stubtest errors have been resolved.
=> ✅ remove scipy 1.16.0rc1 stubtest allowlist

pyproject.toml, uv.lock
https://github.com/DetachHead/basedpyright/releases/tag/v1.29.4
https://github.com/microsoft/pyright/releases/tag/1.1.402
=> ⬆️ bump basedpyright to 1.29.4 (pyright 1.1.402)

scipy-stubs/sparse/_matrix_io.pyi, tests/sparse/test_matrix_io.pyi
This also adds type-tests for `save_npz` and `load_npz`.
=> ✨ `sparse`: simplified gradual `load_npz` return type

pyproject.toml, scipy-stubs/_lib/_util.pyi, scipy-stubs/special/_add_newdocs.pyi, uv.lock
After working around an obscure undocumented new dunder global that mypy doesn't support, stubtest passes:
```bash
$ tox run -e 3.14
3.14: uv-sync> uv sync --locked --python-preference system --no-default-groups --group type --no-editable --reinstall-package=scipy-stubs -p cpython3.14
3.14: commands[0]> stubtest --allowlist=.mypyignore --mypy-config-file=pyproject.toml scipy
Success: no issues found in 1061 modules
3.14: OK (60.80=setup[0.26]+cmd[60.54] seconds)
congratulations :) (60.83 seconds)
```
I did not include 3.14 in the CI testing matrix for performance reasons (no scipy and numpy wheels yet, so both have to be built manually).
=> ✨ preliminary support for Python 3.14

pyproject.toml, uv.lock
https://github.com/astral-sh/ruff/releases/tag/0.12.0
=> ⬆️ bump `ruff` to `0.12.0`

scipy-stubs/sparse/_csr.pyi, scipy-stubs/sparse/_dok.pyi, scipy-stubs/sparse/_typing.pyi, tests/sparse/_types.pyi, tests/sparse/test_csr.pyi, tests/sparse/test_dok.pyi
... and a bunch of other improvements, as well as type-tests for both formats.
---
Closes #622
=> ✨ `sparse`: Improved shape-typing support for CSR and DOK arrays

scipy-stubs/optimize/_minimize.pyi, tests/optimize/minimize.pyi
=> 🐛 `optimize`: fix false rejection of identity functions in `minimize`

scipy-stubs/fft/_realtransforms.pyi
This affects the following public `scipy.fft` functions:
- `dct`
- `dctn`
- `dst`
- `dstn`
- `idct`
- `idctn`
- `idst`
- `idstn`
=> ✨ `fft`: improved discrete sine- and cosine transform return types

.mypyignore, scipy-stubs/optimize/_lbfgsb_py.pyi
Follow-up of #642. 
This also adds deprecation overloads to `optimize.fmin_l_bfgs_b` in case `iprint` or `disp` are used. Apparently these were already deprecated since 1.15.0, but I apparently missed that (as did stubtest).
=> 👽️ scipy 1.16 changes for `optimize.fmin_l_bfgs_b`

scipy-stubs/cluster/vq.pyi, tests/cluster/test_vq.pyi
This affects the following public `scipy..cluster.vq` methods:
- `whiten`
- `vq`
- `kmeans`
- `kmeans2`
=> ✨ `cluster.vq`: improved dtype annotations

.mypyignore, scipy-stubs/cluster/vq.pyi
=> 🐛 `cluster.vq`: Add missing `seed` parameter to `kmeans` and `kmeans2`

.mypyignore, scipy-stubs/interpolate/_polyint.pyi
=> 🐛 `interpolate`: Add missing `seed` kwarg to the `BarycentricInterpolator` constructor

.mypyignore, scipy-stubs/sparse/_construct.pyi
=> 🐛 `sparse`: Add missing `random_state` kwarg to `random_array` and `rand[om]`

.mypyignore, scipy-stubs/spatial/transform/_rotation.pyi
=> 🐛 `spatial.transform`: Add missing `random_state` kwarg to `Rotation.random`

scipy-stubs/signal/windows/_windows.pyi
=> 🐛 `signal`: simplify `get_window` input type

README.md, scipy-stubs/sparse/linalg/_dsolve/_superlu.pyi, scipy-stubs/sparse/linalg/_dsolve/linsolve.pyi, tests/sparse/sparse/test_dsolve.pyi
This affects the following public `scipy.sparse.linalg` functions:
- `spsolve`
- `spsolve_triangular`
- `splu`
- `spilu`
This additionally adds generic type parameters to `scipy.sparse.linalg.SuperLU` (returned by `splu` and `spilu`), making it a generic type.
---
Closes #670
=> ✨ `sparse.linalg`: Improved linear solver function annotations

pyproject.toml, scipy-stubs/optimize/lbfgsb.pyi, scipy-stubs/optimize/optimize.pyi, scipy-stubs/optimize/tnc.pyi, uv.lock
https://github.com/astral-sh/ruff/releases/tag/0.12.1
=> ⬆️ bump `ruff` to `0.12.1`

pyproject.toml, uv.lock
https://github.com/DetachHead/basedpyright/releases/tag/v1.29.5
=> ⬆️ bump `basedpyright` to `1.29.5`

scripts/unstubbed_modules.py
current output:
```
scipy._cyutility
scipy._lib._array_api
scipy._lib._array_api_compat_vendor
scipy._lib._ccallback_c
scipy.cluster._hierarchy
scipy.cluster._optimal_leaf_ordering
scipy.cluster._vq
scipy.integrate._dop
scipy.integrate._lsoda
scipy.integrate._odepack
scipy.integrate._quadpack
scipy.integrate._rules
scipy.integrate._rules._base
scipy.integrate._rules._gauss_kronrod
scipy.integrate._rules._gauss_legendre
scipy.integrate._rules._genz_malik
scipy.integrate._vode
scipy.interpolate._dierckx
scipy.interpolate._fitpack
scipy.interpolate._ppoly
scipy.interpolate._rgi_cython
scipy.io.matlab._mio5_utils
scipy.io.matlab._mio_utils
scipy.io.matlab._streams
scipy.linalg._linalg_pythran
scipy.linalg._matfuncs_schur_sqrtm
scipy.ndimage._nd_image
scipy.ndimage._ni_docstrings …
```
=> 🔨 dev script for listing all (private) unstubbed modules

pyproject.toml, scipy-stubs/_lib/_array_api.pyi, scipy-stubs/_lib/_array_api_compat_vendor.pyi, scipy-stubs/_lib/_ccallback_c.pyi, uv.lock
Stubtest missed these private C/Cython modules for some reason.
=> 🏷️ `_lib`: stub `_ccallback_c` and `_array_api[_compat_vendor]`

scipy-stubs/stats/_ansari_swilk_statistics.pyi, scipy-stubs/stats/_constants.pyi, scipy-stubs/stats/_finite_differences.pyi, scipy-stubs/stats/_qmvnt_cy.pyi, scipy-stubs/stats/_stats.pyi
And with this, all private scipy submodules are stubbed (according to `scripts/unstubbed_modules.py`).
=> 🏷️ `stats`: stub the remaining private modules

scipy-stubs/ndimage/_measurements.pyi, scipy-stubs/stats/_stats.pyi
In preparation for optype 0.11 (hype).
The vast majority of `onp.AnyFloat64DType` uses already included an explcit `| None` where appropriate. In some cases (such as `sparse.linalg.LinearOperator`), there is no `| None`, because we're basically pretending it doesn't exist. When optype 0.11 will be released, we'll no longer have to pretend :).
ref: https://github.com/scipy/scipy-stubs/pull/733#issuecomment-3052821614
cc @JulVandenBroeck
=> ♻️ explicit `onp.AnyFloat64DType | None`

scipy-stubs/linalg/_basic.pyi, tests/linalg/test__basic.pyi
This improves the following "basic" `scipy.linalg` functions:
- `solve`
- `solve_triangular`
- `solve_banded`
- `solveh_banded`
- `solve_toeplitz`
- `solve_circulant`
A total of 240 type-tests have been added for these functions.
=> ✨ `linalg`: improved basic `solve*` annotations

pyproject.toml, uv.lock
https://github.com/astral-sh/ruff/releases/tag/0.12.3
=> ⬆️ bump `ruff` to `0.12.3`

scipy-stubs/interpolate/_bsplines.pyi
The overloads for `make_lsq_spline` in `_bsplines.pyi` had their return types for float and complex `y` inputs swapped.
This change corrects the type hints to ensure that:
- `make_lsq_spline` with a float `y` array correctly returns `BSpline[np.float64]`.
- `make_lsq_spline` with a complex `y` array correctly returns `BSpline[np.complex128]`.
Hopefully this resolves incorrect type checker errors for valid float-only spline creation. 😄
=> 🐛 `interpolate`: Fix incorrect return type for `make_lsq_spline`

scipy-stubs/stats/_stats_py.pyi, tests/stats/test_zscore.pyi
=> ✨ `stats`: improve `zscore` and `gzscore`

pyproject.toml, uv.lock
https://github.com/astral-sh/ruff/releases/tag/0.13.0
=> ⬆️ bump ruff to 0.13.0

scipy-stubs/optimize/_linprog.pyi, tests/.ruff.toml, tests/optimize/test_linprog.pyi
closes #861
This also adds method-specific specialization of `OptimizeResult` for "highs" methods (used by default).
=> ✨ `optimize`: have `linprog` return a specialized `OptimizeResult`

scipy-stubs/optimize/_minimize.pyi
`optimize.minimize` was returning the deprecated `OptimizeResult` from `scipy.optimize.optimize` instead of the one from `scipy.optimize._optimize`, which may have caused false positive deprecation warnings to be reported by type-checkers.
See also https://github.com/scipy/scipy-stubs/pull/881#issuecomment-3287359942
=> 🐛 `optimize`: fix incorrect `OptimizeResult` import

scipy-stubs/_lib/_util.pyi, scipy-stubs/interpolate/_interpolate.pyi, scipy-stubs/io/_mmio.pyi
Caught by [stubdefaulter](https://github.com/JelleZijlstra/stubdefaulter) (`stubdefaulter --only missing-slots -p .`):
- `scipy.io._mmio.MMFile`
- `scipy._lib._util.AxisError`
- `scipy.interpolate._interpolate._PPolyBase`
Towads #895
=> 🐛 missing `__slots__`

.github/workflows/ci.yml, pyproject.toml, uv.lock
=> 👷 validate slots and defaults using stubdefaulter

pyproject.toml
There are no breaking changes according to https://github.com/astral-sh/uv/releases/tag/0.9.0
=> ⬆️ bump `uv_build` to `0.9.0`
