scipy/scipy-stubs

.vscode/settings.json, CODE_OF_CONDUCT.md, SECURITY.md
this adds:
- code of conduct
- security policy (I know..)
=> bureaucracy pro-forma

README.md, pyproject.toml, scipy-stubs/_lib/_ccallback.pyi, scipy-stubs/integrate/__init__.pyi, scipy-stubs/integrate/_bvp.pyi, scipy-stubs/integrate/_ivp/__init__.pyi, scipy-stubs/integrate/_ivp/base.pyi, scipy-stubs/integrate/_ivp/bdf.pyi, scipy-stubs/integrate/_ivp/common.pyi, scipy-stubs/integrate/_ivp/dop853_coefficients.pyi, scipy-stubs/integrate/_ivp/ivp.pyi, scipy-stubs/integrate/_ivp/lsoda.pyi, scipy-stubs/integrate/_ivp/radau.pyi, scipy-stubs/integrate/_ivp/rk.pyi, scipy-stubs/integrate/_odepack_py.pyi, scipy-stubs/integrate/_quad_vec.pyi, scipy-stubs/integrate/_quadpack_py.pyi, scipy-stubs/integrate/_quadrature.pyi, scipy-stubs/integrate/_typing.pyi, scipy-stubs/integrate/dop.pyi, scipy-stubs/integrate/lsoda.pyi, scipy-stubs/integrate/odepack.pyi, scipy-stubs/integrate/quadpack.pyi, scipy-stubs/integrate/vode.pyi
Note that `scipy.integrate._ivp` (which includes `scipy.integrate.solve_ivp`) are technically correct, but are very loosely typed. This will require another iteration.
=> `scipy.integrate`

.github/workflows/ci.yml, pyproject.toml
https://github.com/nat-n/poethepoet
=> add `poe` commands

.pre-commit-config.yaml, pyproject.toml
it can be enabled with 
```console
poetry run pre-commit install
```
to check all files, run
```console
poe pre-commit
```
or equivalently,
```console
poetry run pre-commit run --all-files
```
=> configure pre-commit

scipy-stubs/integrate/__init__.pyi, scipy-stubs/integrate/_ivp/__init__.pyi, scipy-stubs/integrate/_quadrature.pyi, scipy-stubs/integrate/lsoda.pyi, scipy-stubs/integrate/odepack.pyi, scipy-stubs/integrate/quadpack.pyi, tests/stubtest/allowlist.txt
=> deal with deprecated `scipy.integrate` modules

poetry.lock, pyproject.toml
=> made `scipy` optional, and loosened the version restrictions

CONTRIBUTING.md
this is an initial version; I plan to add more details on typing-specific tips & tricks later
towards #50
=> simple contributing guide

scipy-stubs/_lib/_threadsafety.pyi, scipy-stubs/_lib/_uarray/_backend.pyi, scipy-stubs/_lib/_util.pyi, scipy-stubs/_typing.pyi, scipy-stubs/io/_fortran.pyi, scipy-stubs/io/_netcdf.pyi, scipy-stubs/optimize/_differentialevolution.pyi, scipy-stubs/optimize/_shgo.pyi, scipy-stubs/special/_ufuncs.pyi
=> refactor contextmanagers with a type-check-only mixins

README.md, scipy-stubs/_lib/_array_api.pyi, scipy-stubs/_lib/_bunch.pyi, scipy-stubs/_lib/_finite_differences.pyi, scipy-stubs/_lib/_uarray/__init__.pyi, scipy-stubs/_lib/_uarray/_backend.pyi, scipy-stubs/_lib/decorator.pyi, scipy-stubs/_typing.pyi
=> complete and improve `scipy._lib`

README.md, scipy-stubs/spatial/_ckdtree.pyi, scipy-stubs/spatial/_geometric_slerp.pyi, scipy-stubs/spatial/_kdtree.pyi
=> complete `scipy.spatial`

.github/workflows/ci.yml, pyproject.toml
=> configure pyright execution environments

scipy-stubs/integrate/_bvp.pyi, scipy-stubs/integrate/_ivp/base.pyi, scipy-stubs/integrate/_ivp/bdf.pyi, scipy-stubs/integrate/_ivp/common.pyi, scipy-stubs/integrate/_ivp/ivp.pyi, scipy-stubs/integrate/_ivp/lsoda.pyi, scipy-stubs/integrate/_ivp/radau.pyi, scipy-stubs/integrate/_ivp/rk.pyi, scipy-stubs/integrate/_ode.pyi, scipy-stubs/integrate/_tanhsinh.pyi
I left the phase at :waxing_gibbous_moon:, as there is still room for improvement.
With this, there are "only" 4404 `Untyped` uses left.
Resolves #106
=> complete `scipy.integrate`

README.md
=> use utf8 emoji's for pypi compat

.pre-commit-config.yaml, poetry.lock, pyproject.toml
https://github.com/astral-sh/ruff/releases/tag/0.7.1
=> bump `ruff` to `0.7.1`

scipy-stubs/integrate/_quadpack_py.pyi, tests/typetests/integrate_quad.pyi
=> fix `scipy.integrate` quad function parameter types

scipy-stubs/stats/_resampling.pyi
see https://github.com/scipy/scipy/blob/92d2a8592782ee19a1161d0bf3fc2241ba78bb63/scipy/stats/_resampling.py#L1659-L1661
=> fix permutation_test statistic callback type

scipy-stubs/integrate/_quadpack_py.pyi, scipy-stubs/integrate/_typing.pyi
=> sync `integrate._typing.QuadOpts` with `integrate.quad` kwargs

scipy-stubs/spatial/_ckdtree.pyi, scipy-stubs/spatial/_kdtree.pyi
=> fix and improve `scipy.spatial._[c]kdtree`

scipy-stubs/fft/_helper.pyi
=> fix and improve `scipy.fft._helper`

scipy-stubs/optimize/_cobyla_py.pyi, scipy-stubs/optimize/_differentialevolution.pyi, scipy-stubs/optimize/_direct_py.pyi, scipy-stubs/optimize/_dual_annealing.pyi, scipy-stubs/optimize/_isotonic.pyi, scipy-stubs/optimize/_linprog.pyi, scipy-stubs/optimize/_lsq/__init__.pyi, scipy-stubs/optimize/_lsq/bvls.pyi, scipy-stubs/optimize/_lsq/dogbox.pyi, scipy-stubs/optimize/_lsq/givens_elimination.pyi, scipy-stubs/optimize/_lsq/least_squares.pyi, scipy-stubs/optimize/_lsq/lsq_linear.pyi, scipy-stubs/optimize/_lsq/trf.pyi, scipy-stubs/optimize/_lsq/trf_linear.pyi, scipy-stubs/optimize/_milp.pyi, scipy-stubs/optimize/_minimize.pyi, scipy-stubs/optimize/_minpack_py.pyi, scipy-stubs/optimize/_nnls.pyi, scipy-stubs/optimize/_nonlin.pyi, scipy-stubs/optimize/_optimize.pyi, scipy-stubs/optimize/_root.pyi, scipy-stubs/optimize/_shgo.pyi, scipy-stubs/optimize/_trustregion_constr/minimize_trustregion_constr.pyi, scipy-stubs/optimize/_typing.pyi, scipy-stubs/optimize/_zeros_py.pyi
towards #102 (-359)
fixes #134
=> fix and improve `scipy.optimize._optimize`

poetry.lock, pyproject.toml
https://github.com/DetachHead/basedpyright/releases/tag/v1.21.0
=> bump `basedpyright` to `1.21.0`

.github/dependabot.yml
=> configure dependabot to use the correct labels

.pre-commit-config.yaml, CONTRIBUTING.md, poetry.lock, pyproject.toml, tests/README.md
this fixes the compat issues with the latest `mdformat` release
=> bump `mdformat` and `mdformat-pyproject`

.github/release.yml
=> custom auto-generated release notes

scipy-stubs/optimize/_minpack_py.pyi
[docs](https://docs.scipy.org/doc/scipy-1.14.1/reference/generated/scipy.optimize.fixed_point.html)
towards #102 (-3)
=> `optimize`: complete `fixed_point`

scipy-stubs/optimize/_hessian_update_strategy.pyi
docs:
- [`optimize.HessianUpdateStrategy`](https://docs.scipy.org/doc/scipy-1.14.1/reference/generated/scipy.optimize.HessianUpdateStrategy.html)
- [`optimize.BFGS`](https://docs.scipy.org/doc/scipy-1.14.1/reference/generated/scipy.optimize.BFGS.html)
- [`optimize.SR1`](https://docs.scipy.org/doc/scipy-1.14.1/reference/generated/scipy.optimize.SR1.html)
towards #102 (-16)
=> `optimize`: complete `HessianUpdateStrategy`, `BFGS`, and `SR1`

scipy-stubs/optimize/_lsq/common.pyi, scipy-stubs/optimize/_lsq/givens_elimination.pyi, scipy-stubs/optimize/_lsq/trf_linear.pyi
does not affect the public API
towards #102 (-20)
=> `optimize`: complete `_lsq` (private subpackage)

scipy-stubs/optimize/_differentialevolution.pyi
[docs](https://docs.scipy.org/doc/scipy-1.14.1/reference/generated/scipy.optimize.differential_evolution.html)
towards #102 (-61)
=> `optimize`: complete `differential_evolution`

scipy-stubs/optimize/_dual_annealing.pyi
[docs](https://docs.scipy.org/doc/scipy-1.14.1/reference/generated/scipy.optimize.dual_annealing.html)
towards #102 (-85)
=> `optimize`: complete `dual_annealing`

scipy-stubs/optimize/_basinhopping.pyi, scipy-stubs/optimize/_minimize.pyi
This fixes incorrect shape-type of the "jacobian" in `optimize.minimize`. Contrary to what the name suggests, the "jacobian" isn't 2-d in `minimize`, but 1-d (i.e. it's the gradient), since the (multivariate) function always returns a scalar.
=> `optimize`: fix and improve `minimize` and `basinhopping`

scipy-stubs/optimize/_basinhopping.pyi, scipy-stubs/optimize/_dual_annealing.pyi, scipy-stubs/optimize/_shgo.pyi, scipy-stubs/optimize/_typing.pyi
[docs](https://docs.scipy.org/doc/scipy-1.14.1/reference/generated/scipy.optimize.shgo.html)
towards #102 (-91)
=> `optimize`: complete `shgo`, improve `basinhopping`

scipy-stubs/optimize/_linesearch.pyi
[docs](https://docs.scipy.org/doc/scipy-1.14.1/reference/generated/scipy.optimize.line_search.html)
towards #102 (-54)
=> `optimize`: complete `line_search`

scipy-stubs/optimize/_dcsrch.pyi
=> `optimize`: complete `_dcsrch` (private)

scipy-stubs/optimize/_lsap.pyi
[docs](https://docs.scipy.org/doc/scipy-1.14.1/reference/generated/scipy.optimize.linear_sum_assignment.html)
towards #102 (-4)
=> `optimize`: complete `linear_sum_assignment`

scipy-stubs/optimize/_qap.pyi
[docs](https://docs.scipy.org/doc/scipy-1.14.1/reference/generated/scipy.optimize.quadratic_assignment.html)
towards #102
=> ✨ complete `optimize.quadratic_assignment`

poetry.lock, pyproject.toml
https://github.com/jorenham/optype/releases/tag/v0.7.3
=> bump `optype` to `0.7.3`

scipy-stubs/optimize/_numdiff.pyi
=> `optimize`: complete `_numdiff` (private)

scipy-stubs/optimize/_group_columns.pyi
=> `optimize`: complete `_group_columns` (private)

scipy-stubs/optimize/_remove_redundancy.pyi
private and undocumented
towards #102
=> `optimize`: remove `_remove_redundancy` (private)

scipy-stubs/optimize/_cobyla_py.pyi
[docs](https://docs.scipy.org/doc/scipy-1.14.1/reference/generated/scipy.optimize.fmin_cobyla.html)
towards #102 (-5)
=> `optimize`: complete `fmin_cobyla`

scipy-stubs/optimize/_slsqp_py.pyi
[docs](https://docs.scipy.org/doc/scipy-1.14.1/reference/generated/scipy.optimize.fmin_slsqp.html)
resolves #102
=> `optimize`: complete `fmin_slsqp`

CONTRIBUTING.md, pyproject.toml
Small edits to complement #174
=> prevent lock update with tools and `uv` setup guide

README.md
=> 💡 add a comment to prevent breaking the `#installation` permalink

pyproject.toml
running these will now always "rebuild" `scipy-stubs`
=> 🔧 fix caching issue in `poe {mypy,stubtest,typetest}`

scipy-stubs/interpolate/_dfitpack.pyi, scipy-stubs/interpolate/dfitpack.pyi
resolves #268
Not all signatures are precisely typed, as it's very tedious to figure out the signatures from the fortran code. But since it's a private module, it shouldn't matter much (or perhaps at all).
=> ✨ stub `interpolate._dfitpack`

scipy-stubs/interpolate/_ndgriddata.pyi, scipy-stubs/interpolate/interpnd.pyi
=> ✨ complete and improve `interpolate.interpnd`

scipy-stubs/interpolate/_polyint.pyi
This affects the following public members of `scipy.interpolate`:
- `BarycentricInterpolator`
- `KroghInterpolator`
- `barycentric_interpolate`
- `krogh_interpolate`
- `approximate_taylor_polynomial`
closes #101
=> ✨ complete `interpolate._polyint`

README.md
=> 🎤 add podcast to `README.md`

scipy-stubs/sparse/linalg/_eigen/lobpcg/lobpcg.pyi
=> ✨ `sparse.linalg`: complete `lobpcg`

scipy-stubs/sparse/linalg/_eigen/_svds.pyi
=> ✨ `sparse.linalg`: complete `svds`

scipy-stubs/sparse/_construct.pyi
=> ✨ `sparse`: complete `eye[_array]`

scipy-stubs/sparse/_construct.pyi
=> ✨ `sparse`: complete `identity`

scipy-stubs/sparse/_construct.pyi
=> ✨ `sparse`: complete `[sp]diags[_array]`

scipy-stubs/sparse/_matrix_io.pyi
=> ✨ `sparse`: complete `{load,save}_npz`

scipy-stubs/sparse/_sputils.pyi
=> ✨ `sparse`: complete `_sputils.*` (private)

scipy-stubs/sparse/_spfuncs.pyi
=> ✨ `sparse`: complete `_spfuncs.*` (private)

scipy-stubs/sparse/_construct.pyi
=> ✨ `sparse`: complete `rand[om[_array]]`

scipy-stubs/sparse/_construct.pyi
=> ✨ `sparse`: complete `bmat` and `block_{array,diag}`

scipy-stubs/sparse/linalg/_isolve/lsmr.pyi, scipy-stubs/sparse/linalg/_isolve/lsqr.pyi
=> ✨ `sparse`: complete `linalg.ls{m,q}r`

.mypyignore-todo, scipy-stubs/linalg/interpolative.pyi
=> 👽️ `linalg.interpolative`: 1.15.0 support

scipy-stubs/special/_basic.pyi
ref https://github.com/scipy/scipy/pull/22099#issuecomment-2558304671
cc @h-vetinari
---
I've also opened an associated (pun intended) upstream PR: https://github.com/scipy/scipy/pull/22156
=> 💬 `special`: mention the deprecation version in `lpn` and `[c]lpmn`

scipy-stubs/stats/_distn_infrastructure.pyi, tests/stats/test_rv_frozen.pyi
=> 🎨 `stats`: simplify `_distn_infrastructure` with `optype 0.8`

scipy-stubs/_lib/_util.pyi, scipy-stubs/optimize/_linprog.pyi, scipy-stubs/optimize/_milp.pyi, scipy-stubs/optimize/_optimize.pyi, scipy-stubs/optimize/_typing.pyi
This affects the following public `scipy.optimize` members:
- `linprog`
- `milp`
---
closes #398
=> ✨ `optimize`: improved `linprog` and `milp` annotations

scipy-stubs/optimize/_minimize.pyi
=> ✨ `optimize`: method-specific overloads and options for `minimize_scalar`

.github/FUNDING.yml
=> 💸 remove the sponsor button

.vscode/extensions.json, .vscode/settings.json, pyproject.toml, tox.toml
Through the https://marketplace.visualstudio.com/items?itemName=tamasfe.even-better-toml extension.
=> 🔧 `.toml` auto-format config for vscode users

CONTRIBUTING.md
=> 📝 streamlined contributing guide

CONTRIBUTING.md, README.md, pyproject.toml, scipy-stubs/fft/_realtransforms.pyi, scipy-stubs/linalg/_decomp.pyi
=> 🚚 change `jorenham/scipy-stubs` refs to `scipy/scipy-stubs`

scipy-stubs/stats/_distn_infrastructure.pyi
See https://github.com/scipy/scipy-stubs/issues/450 for details.
=> Bugfix: Make `optimizer` argument optional in `scipy.stats.rv_continuous.fit()`

.github/workflows/ci.yml, scripts/generate_matrix.py
this should fix the CI failures
=> 🔨 use `uv` as source of python versions

scipy-stubs/stats/_stats_py.pyi
see scipy/scipy#22405
---
this also cleans up the code a bit
=> ✨ `stats.zmap`: accept complex input and basic shape-typing

scipy-stubs/interpolate/_bsplines.pyi, tests/interpolate/bsplines.pyi
=> 🐛 `scipy.interpolate`: accept scalar input in `BSpline.__call__`

pyproject.toml, uv.lock
https://github.com/jorenham/optype/releases/tag/v0.9.2
=> 📌 upgrade `optype` to `0.9.2`

pyproject.toml
in the hope that this fixes https://github.com/hauntsaninja/mypy_primer/pull/137#pullrequestreview-2686829073
=> 🔧 remove `files` from `[tool.mypy]`

pyproject.toml, scripts/generate_matrix.py
=> 💚 fix mypy_primer failure and mypy/basedmypy compat

scipy-stubs/optimize/_optimize.pyi
=> 🐛 `optimize`: accept a scalar for `x0` in `fmin*`

pyproject.toml, scipy-stubs/stats/_typing.pyi, uv.lock
ruff 0.11.10 and basedpyright 1.19.2
=> ⬆️ bump dev dependencies to latest

scipy-stubs/signal/_short_time_fft.pyi
=> ✨ `signal`: generic `ShortTimeFFT` type-param and improved annotations

.mypyignore-todo, scipy-stubs/signal/__init__.pyi, scipy-stubs/signal/_fir_filter_design.pyi, scipy-stubs/signal/fir_filter_design.pyi
relevant [1.16.0rc1 release notes](https://github.com/scipy/scipy/releases/tag/v1.16.0rc1):
> A new function `scipy.signal.firwin_2d` for the creation of a 2-D FIR Filter
using the 1-D window method was added.
=> 👽️ scipy 1.16 new function `signal.firwin_2d`

scipy-stubs/linalg/_misc.pyi
=> 🩹 stop using `npt.NBitBase` in `linalg._misc`

.github/copilot-instructions.md, .markdownlint.yaml
https://docs.github.com/en/copilot/customizing-copilot/adding-repository-custom-instructions-for-github-copilot
=> 🤖 add instructions for copilot

.github/dependabot.yml, .github/release.yml
I reorganized the labels, so that's why
=> 🤖 update the automated release-note generation

.github/dependabot.yml
=> 👷 update dependabot config to use `uv`

scipy-stubs/datasets/_utils.pyi, tests/datasets/test_download_all.pyi, tests/datasets/test_fetchers.pyi, tests/datasets/test_utils.pyi
This also fixes a minor list-invariance issue in `clear_cache`.
=> ✅ `datasets`: type-tests for `scipy.datasets`

.mdformat.toml, pyproject.toml, uv.lock
=> ➖ remove `mdformat` as dev dependency

.gitignore, CONTRIBUTING.md, lefthook.yml
For modern git hook management https://lefthook.dev/
=> 🧑‍💻 lefthook

README.md
This is something that Copilot is actually pretty good at.
=> 📝 some `README.md` improvements

.mypyignore, scipy-stubs/sparse/linalg/_eigen/_svds.pyi
=> 🐛 `sparse.linalg`: Add missing `random_state` kwarg to `svds`

.markdownlint.yaml, README.md, pyproject.toml
=> 📝 generic type reference docs

scipy-stubs/io/matlab/_mio.pyi
=> 🏷️ `io`: `loadmat` return dict with gradual value types

scipy-stubs/sparse/linalg/_dsolve/linsolve.pyi
=> 🐛 `sparse.linalg`: Fix `factorize` return type annotations

.github/workflows/ci.yml, .github/workflows/publish-pypi.yml
... bringing us closer to [SPEC 5](https://scientific-python.org/specs/spec-0005/) compliance
=> 📌 pin CI action version tags

scipy-stubs/stats/_covariance.pyi
... in case a sequence of builtin ints or floats is passed to one of its constructor methods
=> ✨ `stats`: improved `Covariance` generic type parameter inference

.github/workflows/ci.yml, .vscode/tasks.json, pyproject.toml
=> 🧑‍💻 vscode tasks for basedpyright, mypy, and stubtest

.github/workflows/ci.yml, tests/integrate/test_solve_ivp.pyi
=> 💚 fix CI numpy testing matrix

pyproject.toml, uv.lock
=> ⬆️ bump `mypy` to `1.17.1`

scipy-stubs/stats/_stats_py.pyi, tests/stats/test_mode.pyi
=> ✨ `stats`: improve `mode`

.github/workflows/ci.yml, pyproject.toml, uv.lock
it's quite a bit slower: https://github.com/microsoft/pyright/issues/10832
=> 📌 exclude pyright 1.1.404

.github/workflows/ci.yml, .github/workflows/publish-pypi.yml, pyproject.toml, uv.lock
https://github.com/astral-sh/uv/releases/tag/0.8.13
https://github.com/astral-sh/ruff/releases/tag/0.12.10
=> ⬆️ bump `uv` and `ruff`

.github/workflows/mypy_primer.yml
let's see if this will speed things up
=> 👷 mypy_primer: sharding

.github/workflows/mypy_primer.yml, .github/workflows/mypy_primer_comment.yml
It now uses a single shard, and the `colour` project was removed (for now) because it was taking up the vast majority of the runtime.
=> 👷 mypy_primer: simplified workflow logic

scripts/scipy_usage.py
to get a bit of insight on the most frequently used scipy functionality, which should help prioritize things
=> 🔨 add vibe-coded scipy usage survey script

scipy-stubs/_lib/_ccallback.pyi, scripts/scipy_usage.py
I consider them to be false positives., but that doesn't matter much I suppose, since these errors are gonna have to be dealt with regardless.
=> 🐴 deal with new mypy `1.18.0+dev` errors

scipy-stubs/io/matlab/_mio5_utils.pyi, scipy-stubs/stats/_unuran/unuran_wrapper.pyi
ref: https://github.com/python/mypy/issues/19732#issuecomment-3222223351
=> 🐛 `stats.sampling`: annotate `__cinit__` as `__new__`, not `__init__`

scipy-stubs/integrate/_ivp/base.pyi, scipy-stubs/integrate/_ivp/bdf.pyi
=> 🐛 `integrate`: several `BDF` fixes

README.md
=> 📝 Add bashtage/linearmodels to the list of dependents

pyproject.toml, scipy-stubs/optimize/_lbfgsb_py.pyi, scipy-stubs/spatial/_ckdtree.pyi, uv.lock
https://github.com/astral-sh/ruff/releases/tag/0.14.0
=> ⬆️ bump `ruff` to `0.14.0`

pyproject.toml, uv.lock
=> 🚑 fix `optype` upper bound (again)
